name: Obfuscate JS Files

on:
  push:
    branches: [main]

jobs:
  obfuscate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - Show repository structure
        run: |
          echo "===== REPOSITORY STRUCTURE ====="
          find . -type f -name "*.js" | sort
          echo "================================"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install JavaScript-Obfuscator
        run: npm install -g javascript-obfuscator

      - name: Check obfuscator version and options
        run: |
          javascript-obfuscator --version
          echo "Available options (first few lines):"
          javascript-obfuscator --help | head -20

      - name: Create clean dist directory
        run: |
          rm -rf dist
          mkdir -p dist

      - name: Copy all files to dist
        run: |
          cp -r * dist/ || true
          find dist -type d -name ".git*" -exec rm -rf {} + || true

      - name: Obfuscate JS files with compatible options
        run: |
          find dist -type f -name "*.js" | while read file; do
            echo "Obfuscating: $file"
            # Create a temporary filename
            temp_file="${file}.obfuscated_temp"
            
            # Obfuscate using only widely supported options
            javascript-obfuscator "$file" --output "$temp_file" \
              --compact true \
              --control-flow-flattening true \
              --dead-code-injection true \
              --string-array true \
              --self-defending true
              
            # Only if the obfuscation was successful, replace the original file
            if [ -f "$temp_file" ]; then
              original_size=$(wc -c < "$file")
              new_size=$(wc -c < "$temp_file")
              echo "  Size: $original_size → $new_size bytes"
              
              # Replace original with obfuscated version
              mv "$temp_file" "$file"
            else
              echo "  ⚠️ Failed to obfuscate: $file"
            fi
          done

      - name: Show obfuscated samples
        run: |
          echo "===== OBFUSCATED JS SAMPLES ====="
          find dist -type f -name "*.js" | head -3 | while read file; do
            echo -e "\n>>> $file"
            head -10 "$file"
          done
          echo "================================="

      - name: Add cache busting to HTML files
        run: |
          find dist -type f -name "*.html" | while read file; do
            echo "Adding cache busting to: $file"
            timestamp=$(date +%s)
            sed -i "s/\.js/\.js?v=$timestamp/g" "$file"
            
            # Add verification marker
            sed -i "1s|^|<!-- JS obfuscated: $(date) -->\n|" "$file"
          done

      - name: Verify info.html exists
        run: |
          if [ -f "dist/info.html" ]; then
            echo "✅ info.html exists in dist folder"
          else
            echo "⚠️ info.html not found!"
            find dist -name "*.html" | sort
          fi

          # Create index.html redirect if needed
          if [ ! -f "dist/index.html" ] && [ -f "dist/info.html" ]; then
            echo '<meta http-equiv="refresh" content="0; url=info.html">' > dist/index.html
            echo "Created redirect from index.html to info.html"
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
